"""remove total cost from cart

Revision ID: 1571ca1b8968
Revises: f18c9f80cb36
Create Date: 2026-09-13 14:14:16.446880

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1571ca1b8968'
down_revision: Union[str, Sequence[str], None] = 'f18c9f80cb36'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('cart_items_cart_id_fkey'), 'cart_items', type_='foreignkey')
    op.create_foreign_key(None, 'cart_items', 'carts', ['cart_id'], ['cart_id'], ondelete='CASCADE')
    op.drop_column('carts', 'total_cost')
    op.drop_column('carts', 'quantity_required')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('carts', sa.Column('quantity_required', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('carts', sa.Column('total_cost', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'cart_items', type_='foreignkey')
    op.create_foreign_key(op.f('cart_items_cart_id_fkey'), 'cart_items', 'carts', ['cart_id'], ['cart_id'])
    # ### end Alembic commands ###
